- name: Update system
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS'

- name: Install essential packages
  yum:
    name: "{{ system_init_package[ansible_distribution] }}"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
