- name: Update system
  dnf:
    name: '*'
    state: latest
  
  when: ansible_distribution == 'Rocky'

- name: Install essential packages
  yum:
    name: "{{ system_init_package[ansible_distribution] }}"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

- name: Install container
  block:
  - name: Install yum-utils
    yum: name=yum-utils state=present
  - name: add docker repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - block:
    - name: install containerd
      yum: name=containerd state=present
    - name: install nerdctl
      shell: |
         wget https://github.com/containerd/nerdctl/releases/download/v{{CONTAINER_RUNTIME[nerdctl_version]}}/nerdctl-full-{{CONTAINER_RUNTIME[nerdctl_version]-linux-amd64.tar.gz
        mkdir /usr/local/nerdctl -p
        tar -xf nerdctl-full-{{CONTAINER_RUNTIME[nerdctl_version]}}-linux-amd64.tar.gz -C /usr/local/nerdctl
        echo "export NERDCTL_HOME=/usr/local/nerdctl" >> /etc/profile
        echo "export export PATH=$PATH:$NERDCTL_HOME/bin" >> /etc/profile
        source /etc/profile
    - name: install cni
      shell: |
        wget https://github.com/containernetworking/plugins/releases/download/v{{CONTAINER_RUNTIME[cni_version]}}/cni-plugins-linux-amd64-{{CONTAINER_RUNTIME[cni_version]}}.tgz
        mkdir /opt/cni/bin -p
        tar xf cni-plugins-linux-amd64-{{CONTAINER_RUNTIME[cni_version]}}.tgz -C /opt/cni/bin/
    when: "{{ CONTAINER_RUNTIME }} == 'containerd'"
  - name: install docker
    yum: name=containerd state=present
    when: "{{ CONTAINER_RUNTIME }} == 'docker'"
  when: "{{ CONTAINER_RUNTIME }} == 'true'"