
- import_tasks: Centos-7.yml
  when: ansible_facts.os_family == 'RedHat'
  
- name: Set OS dependent variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.distribution }}.yml'
        - '{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml'
      skip: true
  tags: always